name: karnameh
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.0.0+1

environment:
  sdk: ">= 3.11.0" 

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_riverpod: 
  
  # Local Storage
  hive:
  hive_flutter: 
  
  # Excel Processing
  excel: 
  
  # PDF Generation
  pdf: 
  syncfusion_flutter_pdf:
  syncfusion_flutter_xlsio: 
  
  # File Picker
  file_picker: 
  
  # Responsive UI
  responsive_framework: 
  sizer: 
  flutter_screenutil: 
  
  # Path Provider
  path_provider: 
  
  # Desktop Drop
  desktop_drop: 
  
  # Google Fonts
  google_fonts: 
  persian_number_utility:

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  
  # Hive Generator
  hive_generator: 
  build_runner: 

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - sample_files/final report template.xlsx
    - assets/image/
    
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn-Thin.ttf
          weight: 100
        - asset: assets/fonts/Vazirmatn-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Vazirmatn-Light.ttf
          weight: 300
        - asset: assets/fonts/Vazirmatn-Regular.ttf
          weight: 400
        - asset: assets/fonts/Vazirmatn-Medium.ttf
          weight: 500
        - asset: assets/fonts/Vazirmatn-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Vazirmatn-Bold.ttf
          weight: 700
        - asset: assets/fonts/Vazirmatn-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Vazirmatn-Black.ttf
          weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
